version: "3"
services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      # ダンプしたMySqlファイルを立ち上げ時にマウントする時はこれを使う↓
      # - ./db_data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    env_file: .env

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build: ./
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: .env
    volumes:
      - ./themes/:/var/www/html/wp-content/themes/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=$MYSQL_USER
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  db_data:
    driver: local
